/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool;


import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Apply;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.AreaActivityRegistrationForm;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Campaign;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Connection;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Register;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Report;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Share;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Template;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.User;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Userinfo;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.ApplyRecord;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.AreaActivityRegistrationFormRecord;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.CampaignRecord;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.ConnectionRecord;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.RegisterRecord;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.ReportRecord;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.ShareRecord;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.TemplateRecord;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.UserRecord;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.UserinfoRecord;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>aatool</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ApplyRecord, Integer> IDENTITY_APPLY = Identities0.IDENTITY_APPLY;
    public static final Identity<AreaActivityRegistrationFormRecord, Integer> IDENTITY_AREA_ACTIVITY_REGISTRATION_FORM = Identities0.IDENTITY_AREA_ACTIVITY_REGISTRATION_FORM;
    public static final Identity<CampaignRecord, Integer> IDENTITY_CAMPAIGN = Identities0.IDENTITY_CAMPAIGN;
    public static final Identity<ConnectionRecord, Integer> IDENTITY_CONNECTION = Identities0.IDENTITY_CONNECTION;
    public static final Identity<RegisterRecord, Integer> IDENTITY_REGISTER = Identities0.IDENTITY_REGISTER;
    public static final Identity<ReportRecord, Integer> IDENTITY_REPORT = Identities0.IDENTITY_REPORT;
    public static final Identity<ShareRecord, Integer> IDENTITY_SHARE = Identities0.IDENTITY_SHARE;
    public static final Identity<TemplateRecord, Integer> IDENTITY_TEMPLATE = Identities0.IDENTITY_TEMPLATE;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;
    public static final Identity<UserinfoRecord, Integer> IDENTITY_USERINFO = Identities0.IDENTITY_USERINFO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ApplyRecord> KEY_APPLY_PRIMARY = UniqueKeys0.KEY_APPLY_PRIMARY;
    public static final UniqueKey<AreaActivityRegistrationFormRecord> KEY_AREA_ACTIVITY_REGISTRATION_FORM_PRIMARY = UniqueKeys0.KEY_AREA_ACTIVITY_REGISTRATION_FORM_PRIMARY;
    public static final UniqueKey<AreaActivityRegistrationFormRecord> KEY_AREA_ACTIVITY_REGISTRATION_FORM_BATCHIDANDUSERID = UniqueKeys0.KEY_AREA_ACTIVITY_REGISTRATION_FORM_BATCHIDANDUSERID;
    public static final UniqueKey<CampaignRecord> KEY_CAMPAIGN_PRIMARY = UniqueKeys0.KEY_CAMPAIGN_PRIMARY;
    public static final UniqueKey<ConnectionRecord> KEY_CONNECTION_PRIMARY = UniqueKeys0.KEY_CONNECTION_PRIMARY;
    public static final UniqueKey<RegisterRecord> KEY_REGISTER_PRIMARY = UniqueKeys0.KEY_REGISTER_PRIMARY;
    public static final UniqueKey<ReportRecord> KEY_REPORT_PRIMARY = UniqueKeys0.KEY_REPORT_PRIMARY;
    public static final UniqueKey<ShareRecord> KEY_SHARE_PRIMARY = UniqueKeys0.KEY_SHARE_PRIMARY;
    public static final UniqueKey<TemplateRecord> KEY_TEMPLATE_PRIMARY = UniqueKeys0.KEY_TEMPLATE_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UserinfoRecord> KEY_USERINFO_PRIMARY = UniqueKeys0.KEY_USERINFO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ApplyRecord, Integer> IDENTITY_APPLY = createIdentity(Apply.APPLY, Apply.APPLY.ID);
        public static Identity<AreaActivityRegistrationFormRecord, Integer> IDENTITY_AREA_ACTIVITY_REGISTRATION_FORM = createIdentity(AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM, AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM.ID);
        public static Identity<CampaignRecord, Integer> IDENTITY_CAMPAIGN = createIdentity(Campaign.CAMPAIGN, Campaign.CAMPAIGN.ID);
        public static Identity<ConnectionRecord, Integer> IDENTITY_CONNECTION = createIdentity(Connection.CONNECTION, Connection.CONNECTION.ID);
        public static Identity<RegisterRecord, Integer> IDENTITY_REGISTER = createIdentity(Register.REGISTER, Register.REGISTER.ID);
        public static Identity<ReportRecord, Integer> IDENTITY_REPORT = createIdentity(Report.REPORT, Report.REPORT.ID);
        public static Identity<ShareRecord, Integer> IDENTITY_SHARE = createIdentity(Share.SHARE, Share.SHARE.ID);
        public static Identity<TemplateRecord, Integer> IDENTITY_TEMPLATE = createIdentity(Template.TEMPLATE, Template.TEMPLATE.ID);
        public static Identity<UserRecord, Integer> IDENTITY_USER = createIdentity(User.USER, User.USER.ID);
        public static Identity<UserinfoRecord, Integer> IDENTITY_USERINFO = createIdentity(Userinfo.USERINFO, Userinfo.USERINFO.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ApplyRecord> KEY_APPLY_PRIMARY = createUniqueKey(Apply.APPLY, "KEY_apply_PRIMARY", Apply.APPLY.ID);
        public static final UniqueKey<AreaActivityRegistrationFormRecord> KEY_AREA_ACTIVITY_REGISTRATION_FORM_PRIMARY = createUniqueKey(AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM, "KEY_area_activity_registration_form_PRIMARY", AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM.ID);
        public static final UniqueKey<AreaActivityRegistrationFormRecord> KEY_AREA_ACTIVITY_REGISTRATION_FORM_BATCHIDANDUSERID = createUniqueKey(AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM, "KEY_area_activity_registration_form_batchIdAndUserId", AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM.BATCHID, AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM.USERID);
        public static final UniqueKey<CampaignRecord> KEY_CAMPAIGN_PRIMARY = createUniqueKey(Campaign.CAMPAIGN, "KEY_campaign_PRIMARY", Campaign.CAMPAIGN.ID);
        public static final UniqueKey<ConnectionRecord> KEY_CONNECTION_PRIMARY = createUniqueKey(Connection.CONNECTION, "KEY_connection_PRIMARY", Connection.CONNECTION.ID);
        public static final UniqueKey<RegisterRecord> KEY_REGISTER_PRIMARY = createUniqueKey(Register.REGISTER, "KEY_register_PRIMARY", Register.REGISTER.ID);
        public static final UniqueKey<ReportRecord> KEY_REPORT_PRIMARY = createUniqueKey(Report.REPORT, "KEY_report_PRIMARY", Report.REPORT.ID);
        public static final UniqueKey<ShareRecord> KEY_SHARE_PRIMARY = createUniqueKey(Share.SHARE, "KEY_share_PRIMARY", Share.SHARE.ID);
        public static final UniqueKey<TemplateRecord> KEY_TEMPLATE_PRIMARY = createUniqueKey(Template.TEMPLATE, "KEY_template_PRIMARY", Template.TEMPLATE.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
        public static final UniqueKey<UserinfoRecord> KEY_USERINFO_PRIMARY = createUniqueKey(Userinfo.USERINFO, "KEY_userinfo_PRIMARY", Userinfo.USERINFO.ID);
    }
}
