/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool;


import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Apply;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.AreaActivityRegistrationForm;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Campaign;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Connection;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Register;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Report;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Share;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Template;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.User;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Userinfo;


/**
 * Convenience access to all tables in aatool
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>aatool.apply</code>.
     */
    public static final Apply APPLY = org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Apply.APPLY;

    /**
     * The table <code>aatool.area_activity_registration_form</code>.
     */
    public static final AreaActivityRegistrationForm AREA_ACTIVITY_REGISTRATION_FORM = org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM;

    /**
     * The table <code>aatool.campaign</code>.
     */
    public static final Campaign CAMPAIGN = org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Campaign.CAMPAIGN;

    /**
     * The table <code>aatool.connection</code>.
     */
    public static final Connection CONNECTION = org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Connection.CONNECTION;

    /**
     * The table <code>aatool.register</code>.
     */
    public static final Register REGISTER = org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Register.REGISTER;

    /**
     * The table <code>aatool.report</code>.
     */
    public static final Report REPORT = org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Report.REPORT;

    /**
     * The table <code>aatool.share</code>.
     */
    public static final Share SHARE = org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Share.SHARE;

    /**
     * The table <code>aatool.template</code>.
     */
    public static final Template TEMPLATE = org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Template.TEMPLATE;

    /**
     * The table <code>aatool.user</code>.
     */
    public static final User USER = org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.User.USER;

    /**
     * The table <code>aatool.userinfo</code>.
     */
    public static final Userinfo USERINFO = org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Userinfo.USERINFO;
}
