/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.tools.dashboard.myspace.jooq.tables.records;


import javax.annotation.Generated;

import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Gallerydetail;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GallerydetailRecord extends UpdatableRecordImpl<GallerydetailRecord> implements Record9<Integer, Integer, Integer, Integer, String, String, String, Integer, String> {

    private static final long serialVersionUID = 2129639455;

    /**
     * Setter for <code>myspace2.gallerydetail.id</code>.
     */
    public GallerydetailRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallerydetail.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>myspace2.gallerydetail.galleryId</code>.
     */
    public GallerydetailRecord setGalleryid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallerydetail.galleryId</code>.
     */
    public Integer getGalleryid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>myspace2.gallerydetail.isCover</code>.
     */
    public GallerydetailRecord setIscover(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallerydetail.isCover</code>.
     */
    public Integer getIscover() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>myspace2.gallerydetail.status</code>.
     */
    public GallerydetailRecord setStatus(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallerydetail.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>myspace2.gallerydetail.description</code>.
     */
    public GallerydetailRecord setDescription(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallerydetail.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>myspace2.gallerydetail.galleryKey</code>.
     */
    public GallerydetailRecord setGallerykey(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallerydetail.galleryKey</code>.
     */
    public String getGallerykey() {
        return (String) get(5);
    }

    /**
     * Setter for <code>myspace2.gallerydetail.smallGalleryKey</code>.
     */
    public GallerydetailRecord setSmallgallerykey(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallerydetail.smallGalleryKey</code>.
     */
    public String getSmallgallerykey() {
        return (String) get(6);
    }

    /**
     * Setter for <code>myspace2.gallerydetail.orderNo</code>.
     */
    public GallerydetailRecord setOrderno(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallerydetail.orderNo</code>.
     */
    public Integer getOrderno() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>myspace2.gallerydetail.chooseTemplate</code>.
     */
    public GallerydetailRecord setChoosetemplate(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallerydetail.chooseTemplate</code>.
     */
    public String getChoosetemplate() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, String, String, String, Integer, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, String, String, String, Integer, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Gallerydetail.GALLERYDETAIL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Gallerydetail.GALLERYDETAIL.GALLERYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Gallerydetail.GALLERYDETAIL.ISCOVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Gallerydetail.GALLERYDETAIL.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Gallerydetail.GALLERYDETAIL.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Gallerydetail.GALLERYDETAIL.GALLERYKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Gallerydetail.GALLERYDETAIL.SMALLGALLERYKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Gallerydetail.GALLERYDETAIL.ORDERNO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Gallerydetail.GALLERYDETAIL.CHOOSETEMPLATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getGalleryid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIscover();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getGallerykey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSmallgallerykey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getOrderno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getChoosetemplate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GallerydetailRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GallerydetailRecord value2(Integer value) {
        setGalleryid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GallerydetailRecord value3(Integer value) {
        setIscover(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GallerydetailRecord value4(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GallerydetailRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GallerydetailRecord value6(String value) {
        setGallerykey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GallerydetailRecord value7(String value) {
        setSmallgallerykey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GallerydetailRecord value8(Integer value) {
        setOrderno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GallerydetailRecord value9(String value) {
        setChoosetemplate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GallerydetailRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, String value7, Integer value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GallerydetailRecord
     */
    public GallerydetailRecord() {
        super(Gallerydetail.GALLERYDETAIL);
    }

    /**
     * Create a detached, initialised GallerydetailRecord
     */
    public GallerydetailRecord(Integer id, Integer galleryid, Integer iscover, Integer status, String description, String gallerykey, String smallgallerykey, Integer orderno, String choosetemplate) {
        super(Gallerydetail.GALLERYDETAIL);

        set(0, id);
        set(1, galleryid);
        set(2, iscover);
        set(3, status);
        set(4, description);
        set(5, gallerykey);
        set(6, smallgallerykey);
        set(7, orderno);
        set(8, choosetemplate);
    }
}
