/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.tools.dashboard.myspace.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Gallery;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GalleryRecord extends UpdatableRecordImpl<GalleryRecord> implements Record13<Integer, String, String, Integer, String, String, String, Integer, String, Timestamp, Integer, Timestamp, Integer> {

    private static final long serialVersionUID = 1234523130;

    /**
     * Setter for <code>myspace2.gallery.id</code>.
     */
    public GalleryRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallery.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>myspace2.gallery.openId</code>.
     */
    public GalleryRecord setOpenid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallery.openId</code>.
     */
    public String getOpenid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>myspace2.gallery.ada</code>.
     */
    public GalleryRecord setAda(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallery.ada</code>.
     */
    public String getAda() {
        return (String) get(2);
    }

    /**
     * Setter for <code>myspace2.gallery.attachmentId</code>.
     */
    public GalleryRecord setAttachmentid(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallery.attachmentId</code>.
     */
    public Integer getAttachmentid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>myspace2.gallery.chooseMusic</code>.
     */
    public GalleryRecord setChoosemusic(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallery.chooseMusic</code>.
     */
    public String getChoosemusic() {
        return (String) get(4);
    }

    /**
     * Setter for <code>myspace2.gallery.galleryName</code>.
     */
    public GalleryRecord setGalleryname(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallery.galleryName</code>.
     */
    public String getGalleryname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>myspace2.gallery.description</code>.
     */
    public GalleryRecord setDescription(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallery.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>myspace2.gallery.status</code>.
     */
    public GalleryRecord setStatus(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallery.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>myspace2.gallery.qrCodeKey</code>.
     */
    public GalleryRecord setQrcodekey(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallery.qrCodeKey</code>.
     */
    public String getQrcodekey() {
        return (String) get(8);
    }

    /**
     * Setter for <code>myspace2.gallery.createTime</code>.
     */
    public GalleryRecord setCreatetime(Timestamp value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallery.createTime</code>.
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>myspace2.gallery.creatorId</code>.
     */
    public GalleryRecord setCreatorid(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallery.creatorId</code>.
     */
    public Integer getCreatorid() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>myspace2.gallery.updateTime</code>.
     */
    public GalleryRecord setUpdatetime(Timestamp value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallery.updateTime</code>.
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>myspace2.gallery.modifierId</code>.
     */
    public GalleryRecord setModifierid(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>myspace2.gallery.modifierId</code>.
     */
    public Integer getModifierid() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, Integer, String, String, String, Integer, String, Timestamp, Integer, Timestamp, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, Integer, String, String, String, Integer, String, Timestamp, Integer, Timestamp, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Gallery.GALLERY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Gallery.GALLERY.OPENID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Gallery.GALLERY.ADA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Gallery.GALLERY.ATTACHMENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Gallery.GALLERY.CHOOSEMUSIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Gallery.GALLERY.GALLERYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Gallery.GALLERY.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Gallery.GALLERY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Gallery.GALLERY.QRCODEKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Gallery.GALLERY.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Gallery.GALLERY.CREATORID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Gallery.GALLERY.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Gallery.GALLERY.MODIFIERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAda();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAttachmentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getChoosemusic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getGalleryname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getQrcodekey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getCreatorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getModifierid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord value2(String value) {
        setOpenid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord value3(String value) {
        setAda(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord value4(Integer value) {
        setAttachmentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord value5(String value) {
        setChoosemusic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord value6(String value) {
        setGalleryname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord value8(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord value9(String value) {
        setQrcodekey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord value10(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord value11(Integer value) {
        setCreatorid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord value12(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord value13(Integer value) {
        setModifierid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GalleryRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, String value7, Integer value8, String value9, Timestamp value10, Integer value11, Timestamp value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GalleryRecord
     */
    public GalleryRecord() {
        super(Gallery.GALLERY);
    }

    /**
     * Create a detached, initialised GalleryRecord
     */
    public GalleryRecord(Integer id, String openid, String ada, Integer attachmentid, String choosemusic, String galleryname, String description, Integer status, String qrcodekey, Timestamp createtime, Integer creatorid, Timestamp updatetime, Integer modifierid) {
        super(Gallery.GALLERY);

        set(0, id);
        set(1, openid);
        set(2, ada);
        set(3, attachmentid);
        set(4, choosemusic);
        set(5, galleryname);
        set(6, description);
        set(7, status);
        set(8, qrcodekey);
        set(9, createtime);
        set(10, creatorid);
        set(11, updatetime);
        set(12, modifierid);
    }
}
