/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.Aatool;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.Keys;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.ApplyRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Apply extends TableImpl<ApplyRecord> {

    private static final long serialVersionUID = 1305141713;

    /**
     * The reference instance of <code>aatool.apply</code>
     */
    public static final Apply APPLY = new Apply();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ApplyRecord> getRecordType() {
        return ApplyRecord.class;
    }

    /**
     * The column <code>aatool.apply.id</code>.
     */
    public final TableField<ApplyRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>aatool.apply.shareId</code>.
     */
    public final TableField<ApplyRecord, Integer> SHAREID = createField("shareId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>aatool.apply.campaignId</code>.
     */
    public final TableField<ApplyRecord, Integer> CAMPAIGNID = createField("campaignId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>aatool.apply.userId</code>.
     */
    public final TableField<ApplyRecord, Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>aatool.apply.memo</code>.
     */
    public final TableField<ApplyRecord, String> MEMO = createField("memo", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>aatool.apply.createTime</code>.
     */
    public final TableField<ApplyRecord, LocalDateTime> CREATETIME = createField("createTime", org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>aatool.apply.status</code>.
     */
    public final TableField<ApplyRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>aatool.apply</code> table reference
     */
    public Apply() {
        this("apply", null);
    }

    /**
     * Create an aliased <code>aatool.apply</code> table reference
     */
    public Apply(String alias) {
        this(alias, APPLY);
    }

    private Apply(String alias, Table<ApplyRecord> aliased) {
        this(alias, aliased, null);
    }

    private Apply(String alias, Table<ApplyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Aatool.AATOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ApplyRecord, Integer> getIdentity() {
        return Keys.IDENTITY_APPLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ApplyRecord> getPrimaryKey() {
        return Keys.KEY_APPLY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ApplyRecord>> getKeys() {
        return Arrays.<UniqueKey<ApplyRecord>>asList(Keys.KEY_APPLY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Apply as(String alias) {
        return new Apply(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Apply rename(String name) {
        return new Apply(name, null);
    }
}
