/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.Aatool;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.Keys;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.ConnectionRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Connection extends TableImpl<ConnectionRecord> {

    private static final long serialVersionUID = 1704776240;

    /**
     * The reference instance of <code>aatool.connection</code>
     */
    public static final Connection CONNECTION = new Connection();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConnectionRecord> getRecordType() {
        return ConnectionRecord.class;
    }

    /**
     * The column <code>aatool.connection.id</code>.
     */
    public final TableField<ConnectionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>aatool.connection.userId</code>.
     */
    public final TableField<ConnectionRecord, Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>aatool.connection.shareId</code>.
     */
    public final TableField<ConnectionRecord, Integer> SHAREID = createField("shareId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>aatool.connection.campaignId</code>.
     */
    public final TableField<ConnectionRecord, Integer> CAMPAIGNID = createField("campaignId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>aatool.connection.createType</code>.
     */
    public final TableField<ConnectionRecord, String> CREATETYPE = createField("createType", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>aatool.connection.createTime</code>.
     */
    public final TableField<ConnectionRecord, LocalDateTime> CREATETIME = createField("createTime", org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>aatool.connection</code> table reference
     */
    public Connection() {
        this("connection", null);
    }

    /**
     * Create an aliased <code>aatool.connection</code> table reference
     */
    public Connection(String alias) {
        this(alias, CONNECTION);
    }

    private Connection(String alias, Table<ConnectionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Connection(String alias, Table<ConnectionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Aatool.AATOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ConnectionRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CONNECTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ConnectionRecord> getPrimaryKey() {
        return Keys.KEY_CONNECTION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ConnectionRecord>> getKeys() {
        return Arrays.<UniqueKey<ConnectionRecord>>asList(Keys.KEY_CONNECTION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Connection as(String alias) {
        return new Connection(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Connection rename(String name) {
        return new Connection(name, null);
    }
}
