/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.Aatool;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.Keys;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.RegisterRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Register extends TableImpl<RegisterRecord> {

    private static final long serialVersionUID = 1975159381;

    /**
     * The reference instance of <code>aatool.register</code>
     */
    public static final Register REGISTER = new Register();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RegisterRecord> getRecordType() {
        return RegisterRecord.class;
    }

    /**
     * The column <code>aatool.register.id</code>.
     */
    public final TableField<RegisterRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>aatool.register.campaignId</code>.
     */
    public final TableField<RegisterRecord, Integer> CAMPAIGNID = createField("campaignId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>aatool.register.userId</code>.
     */
    public final TableField<RegisterRecord, Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>aatool.register.createTime</code>.
     */
    public final TableField<RegisterRecord, LocalDateTime> CREATETIME = createField("createTime", org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>aatool.register.hasApply</code>.
     */
    public final TableField<RegisterRecord, Integer> HASAPPLY = createField("hasApply", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>aatool.register.status</code>.
     */
    public final TableField<RegisterRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>aatool.register</code> table reference
     */
    public Register() {
        this("register", null);
    }

    /**
     * Create an aliased <code>aatool.register</code> table reference
     */
    public Register(String alias) {
        this(alias, REGISTER);
    }

    private Register(String alias, Table<RegisterRecord> aliased) {
        this(alias, aliased, null);
    }

    private Register(String alias, Table<RegisterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Aatool.AATOOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RegisterRecord, Integer> getIdentity() {
        return Keys.IDENTITY_REGISTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RegisterRecord> getPrimaryKey() {
        return Keys.KEY_REGISTER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RegisterRecord>> getKeys() {
        return Arrays.<UniqueKey<RegisterRecord>>asList(Keys.KEY_REGISTER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Register as(String alias) {
        return new Register(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Register rename(String name) {
        return new Register(name, null);
    }
}
