/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Campaign implements Serializable {

    private static final long serialVersionUID = -1015117698;

    private Integer       id;
    private String        title;
    private String        location;
    private String        digest;
    private LocalDateTime applydeadline;
    private LocalDateTime starttime;
    private LocalDateTime endtime;
    private Integer       limit;
    private String        coverimagekey;
    private String        chargeimagekey;
    private String        content;
    private Integer       cancoverworkshop;
    private Integer       ischarge;
    private Integer       templateid;
    private String        ada;
    private String        workshopurl;
    private String        workshopname;
    private String        workshopheadimgurl;
    private String        workshopwelcomeword;
    private Integer       status;
    private Integer       createuserid;
    private LocalDateTime createtime;
    private String        sharedigest;
    private String        organizers;
    private String        ticket;

    public Campaign() {}

    public Campaign(Campaign value) {
        this.id = value.id;
        this.title = value.title;
        this.location = value.location;
        this.digest = value.digest;
        this.applydeadline = value.applydeadline;
        this.starttime = value.starttime;
        this.endtime = value.endtime;
        this.limit = value.limit;
        this.coverimagekey = value.coverimagekey;
        this.chargeimagekey = value.chargeimagekey;
        this.content = value.content;
        this.cancoverworkshop = value.cancoverworkshop;
        this.ischarge = value.ischarge;
        this.templateid = value.templateid;
        this.ada = value.ada;
        this.workshopurl = value.workshopurl;
        this.workshopname = value.workshopname;
        this.workshopheadimgurl = value.workshopheadimgurl;
        this.workshopwelcomeword = value.workshopwelcomeword;
        this.status = value.status;
        this.createuserid = value.createuserid;
        this.createtime = value.createtime;
        this.sharedigest = value.sharedigest;
        this.organizers = value.organizers;
        this.ticket = value.ticket;
    }

    public Campaign(
        Integer       id,
        String        title,
        String        location,
        String        digest,
        LocalDateTime applydeadline,
        LocalDateTime starttime,
        LocalDateTime endtime,
        Integer       limit,
        String        coverimagekey,
        String        chargeimagekey,
        String        content,
        Integer       cancoverworkshop,
        Integer       ischarge,
        Integer       templateid,
        String        ada,
        String        workshopurl,
        String        workshopname,
        String        workshopheadimgurl,
        String        workshopwelcomeword,
        Integer       status,
        Integer       createuserid,
        LocalDateTime createtime,
        String        sharedigest,
        String        organizers,
        String        ticket
    ) {
        this.id = id;
        this.title = title;
        this.location = location;
        this.digest = digest;
        this.applydeadline = applydeadline;
        this.starttime = starttime;
        this.endtime = endtime;
        this.limit = limit;
        this.coverimagekey = coverimagekey;
        this.chargeimagekey = chargeimagekey;
        this.content = content;
        this.cancoverworkshop = cancoverworkshop;
        this.ischarge = ischarge;
        this.templateid = templateid;
        this.ada = ada;
        this.workshopurl = workshopurl;
        this.workshopname = workshopname;
        this.workshopheadimgurl = workshopheadimgurl;
        this.workshopwelcomeword = workshopwelcomeword;
        this.status = status;
        this.createuserid = createuserid;
        this.createtime = createtime;
        this.sharedigest = sharedigest;
        this.organizers = organizers;
        this.ticket = ticket;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getDigest() {
        return this.digest;
    }

    public void setDigest(String digest) {
        this.digest = digest;
    }

    public LocalDateTime getApplydeadline() {
        return this.applydeadline;
    }

    public void setApplydeadline(LocalDateTime applydeadline) {
        this.applydeadline = applydeadline;
    }

    public LocalDateTime getStarttime() {
        return this.starttime;
    }

    public void setStarttime(LocalDateTime starttime) {
        this.starttime = starttime;
    }

    public LocalDateTime getEndtime() {
        return this.endtime;
    }

    public void setEndtime(LocalDateTime endtime) {
        this.endtime = endtime;
    }

    public Integer getLimit() {
        return this.limit;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public String getCoverimagekey() {
        return this.coverimagekey;
    }

    public void setCoverimagekey(String coverimagekey) {
        this.coverimagekey = coverimagekey;
    }

    public String getChargeimagekey() {
        return this.chargeimagekey;
    }

    public void setChargeimagekey(String chargeimagekey) {
        this.chargeimagekey = chargeimagekey;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getCancoverworkshop() {
        return this.cancoverworkshop;
    }

    public void setCancoverworkshop(Integer cancoverworkshop) {
        this.cancoverworkshop = cancoverworkshop;
    }

    public Integer getIscharge() {
        return this.ischarge;
    }

    public void setIscharge(Integer ischarge) {
        this.ischarge = ischarge;
    }

    public Integer getTemplateid() {
        return this.templateid;
    }

    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    public String getAda() {
        return this.ada;
    }

    public void setAda(String ada) {
        this.ada = ada;
    }

    public String getWorkshopurl() {
        return this.workshopurl;
    }

    public void setWorkshopurl(String workshopurl) {
        this.workshopurl = workshopurl;
    }

    public String getWorkshopname() {
        return this.workshopname;
    }

    public void setWorkshopname(String workshopname) {
        this.workshopname = workshopname;
    }

    public String getWorkshopheadimgurl() {
        return this.workshopheadimgurl;
    }

    public void setWorkshopheadimgurl(String workshopheadimgurl) {
        this.workshopheadimgurl = workshopheadimgurl;
    }

    public String getWorkshopwelcomeword() {
        return this.workshopwelcomeword;
    }

    public void setWorkshopwelcomeword(String workshopwelcomeword) {
        this.workshopwelcomeword = workshopwelcomeword;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getCreateuserid() {
        return this.createuserid;
    }

    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    public LocalDateTime getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(LocalDateTime createtime) {
        this.createtime = createtime;
    }

    public String getSharedigest() {
        return this.sharedigest;
    }

    public void setSharedigest(String sharedigest) {
        this.sharedigest = sharedigest;
    }

    public String getOrganizers() {
        return this.organizers;
    }

    public void setOrganizers(String organizers) {
        this.organizers = organizers;
    }

    public String getTicket() {
        return this.ticket;
    }

    public void setTicket(String ticket) {
        this.ticket = ticket;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Campaign (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(location);
        sb.append(", ").append(digest);
        sb.append(", ").append(applydeadline);
        sb.append(", ").append(starttime);
        sb.append(", ").append(endtime);
        sb.append(", ").append(limit);
        sb.append(", ").append(coverimagekey);
        sb.append(", ").append(chargeimagekey);
        sb.append(", ").append(content);
        sb.append(", ").append(cancoverworkshop);
        sb.append(", ").append(ischarge);
        sb.append(", ").append(templateid);
        sb.append(", ").append(ada);
        sb.append(", ").append(workshopurl);
        sb.append(", ").append(workshopname);
        sb.append(", ").append(workshopheadimgurl);
        sb.append(", ").append(workshopwelcomeword);
        sb.append(", ").append(status);
        sb.append(", ").append(createuserid);
        sb.append(", ").append(createtime);
        sb.append(", ").append(sharedigest);
        sb.append(", ").append(organizers);
        sb.append(", ").append(ticket);

        sb.append(")");
        return sb.toString();
    }
}
