/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Register implements Serializable {

    private static final long serialVersionUID = 1920639248;

    private Integer       id;
    private Integer       campaignid;
    private Integer       userid;
    private LocalDateTime createtime;
    private Integer       hasapply;
    private Integer       status;

    public Register() {}

    public Register(Register value) {
        this.id = value.id;
        this.campaignid = value.campaignid;
        this.userid = value.userid;
        this.createtime = value.createtime;
        this.hasapply = value.hasapply;
        this.status = value.status;
    }

    public Register(
        Integer       id,
        Integer       campaignid,
        Integer       userid,
        LocalDateTime createtime,
        Integer       hasapply,
        Integer       status
    ) {
        this.id = id;
        this.campaignid = campaignid;
        this.userid = userid;
        this.createtime = createtime;
        this.hasapply = hasapply;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCampaignid() {
        return this.campaignid;
    }

    public void setCampaignid(Integer campaignid) {
        this.campaignid = campaignid;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public LocalDateTime getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(LocalDateTime createtime) {
        this.createtime = createtime;
    }

    public Integer getHasapply() {
        return this.hasapply;
    }

    public void setHasapply(Integer hasapply) {
        this.hasapply = hasapply;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Register (");

        sb.append(id);
        sb.append(", ").append(campaignid);
        sb.append(", ").append(userid);
        sb.append(", ").append(createtime);
        sb.append(", ").append(hasapply);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
