/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Report implements Serializable {

    private static final long serialVersionUID = 1695947963;

    private Integer       id;
    private Integer       campaignid;
    private Integer       userid;
    private String        content;
    private LocalDateTime createtime;

    public Report() {}

    public Report(Report value) {
        this.id = value.id;
        this.campaignid = value.campaignid;
        this.userid = value.userid;
        this.content = value.content;
        this.createtime = value.createtime;
    }

    public Report(
        Integer       id,
        Integer       campaignid,
        Integer       userid,
        String        content,
        LocalDateTime createtime
    ) {
        this.id = id;
        this.campaignid = campaignid;
        this.userid = userid;
        this.content = content;
        this.createtime = createtime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCampaignid() {
        return this.campaignid;
    }

    public void setCampaignid(Integer campaignid) {
        this.campaignid = campaignid;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public LocalDateTime getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(LocalDateTime createtime) {
        this.createtime = createtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Report (");

        sb.append(id);
        sb.append(", ").append(campaignid);
        sb.append(", ").append(userid);
        sb.append(", ").append(content);
        sb.append(", ").append(createtime);

        sb.append(")");
        return sb.toString();
    }
}
