/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userinfo implements Serializable {

    private static final long serialVersionUID = -1896422714;

    private Integer       id;
    private Integer       userid;
    private String        name;
    private String        phone;
    private LocalDateTime createtime;

    public Userinfo() {}

    public Userinfo(Userinfo value) {
        this.id = value.id;
        this.userid = value.userid;
        this.name = value.name;
        this.phone = value.phone;
        this.createtime = value.createtime;
    }

    public Userinfo(
        Integer       id,
        Integer       userid,
        String        name,
        String        phone,
        LocalDateTime createtime
    ) {
        this.id = id;
        this.userid = userid;
        this.name = name;
        this.phone = phone;
        this.createtime = createtime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public LocalDateTime getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(LocalDateTime createtime) {
        this.createtime = createtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Userinfo (");

        sb.append(id);
        sb.append(", ").append(userid);
        sb.append(", ").append(name);
        sb.append(", ").append(phone);
        sb.append(", ").append(createtime);

        sb.append(")");
        return sb.toString();
    }
}
