/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -166166674;

    private Integer       id;
    private Integer       isabo;
    private String        openid;
    private String        nickname;
    private String        headimgurl;
    private LocalDateTime createtime;
    private String        invitecode;
    private String        ada;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.isabo = value.isabo;
        this.openid = value.openid;
        this.nickname = value.nickname;
        this.headimgurl = value.headimgurl;
        this.createtime = value.createtime;
        this.invitecode = value.invitecode;
        this.ada = value.ada;
    }

    public User(
        Integer       id,
        Integer       isabo,
        String        openid,
        String        nickname,
        String        headimgurl,
        LocalDateTime createtime,
        String        invitecode,
        String        ada
    ) {
        this.id = id;
        this.isabo = isabo;
        this.openid = openid;
        this.nickname = nickname;
        this.headimgurl = headimgurl;
        this.createtime = createtime;
        this.invitecode = invitecode;
        this.ada = ada;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIsabo() {
        return this.isabo;
    }

    public void setIsabo(Integer isabo) {
        this.isabo = isabo;
    }

    public String getOpenid() {
        return this.openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getHeadimgurl() {
        return this.headimgurl;
    }

    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }

    public LocalDateTime getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(LocalDateTime createtime) {
        this.createtime = createtime;
    }

    public String getInvitecode() {
        return this.invitecode;
    }

    public void setInvitecode(String invitecode) {
        this.invitecode = invitecode;
    }

    public String getAda() {
        return this.ada;
    }

    public void setAda(String ada) {
        this.ada = ada;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(isabo);
        sb.append(", ").append(openid);
        sb.append(", ").append(nickname);
        sb.append(", ").append(headimgurl);
        sb.append(", ").append(createtime);
        sb.append(", ").append(invitecode);
        sb.append(", ").append(ada);

        sb.append(")");
        return sb.toString();
    }
}
