/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.tools.dashboard.myspace.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Attachment implements Serializable {

    private static final long serialVersionUID = -919507030;

    private Integer   id;
    private String    attkey;
    private String    attname;
    private Integer   type;
    private Timestamp createtime;

    public Attachment() {}

    public Attachment(Attachment value) {
        this.id = value.id;
        this.attkey = value.attkey;
        this.attname = value.attname;
        this.type = value.type;
        this.createtime = value.createtime;
    }

    public Attachment(
        Integer   id,
        String    attkey,
        String    attname,
        Integer   type,
        Timestamp createtime
    ) {
        this.id = id;
        this.attkey = attkey;
        this.attname = attname;
        this.type = type;
        this.createtime = createtime;
    }

    public Integer getId() {
        return this.id;
    }

    public Attachment setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getAttkey() {
        return this.attkey;
    }

    public Attachment setAttkey(String attkey) {
        this.attkey = attkey;
        return this;
    }

    public String getAttname() {
        return this.attname;
    }

    public Attachment setAttname(String attname) {
        this.attname = attname;
        return this;
    }

    public Integer getType() {
        return this.type;
    }

    public Attachment setType(Integer type) {
        this.type = type;
        return this;
    }

    public Timestamp getCreatetime() {
        return this.createtime;
    }

    public Attachment setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Attachment (");

        sb.append(id);
        sb.append(", ").append(attkey);
        sb.append(", ").append(attname);
        sb.append(", ").append(type);
        sb.append(", ").append(createtime);

        sb.append(")");
        return sb.toString();
    }
}
