/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.tools.dashboard.myspace.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Clicklike implements Serializable {

    private static final long serialVersionUID = 355510574;

    private Integer   id;
    private Integer   galleryid;
    private Integer   detailid;
    private Integer   userid;
    private String    openid;
    private String    nickname;
    private String    headimgurl;
    private Timestamp createtime;

    public Clicklike() {}

    public Clicklike(Clicklike value) {
        this.id = value.id;
        this.galleryid = value.galleryid;
        this.detailid = value.detailid;
        this.userid = value.userid;
        this.openid = value.openid;
        this.nickname = value.nickname;
        this.headimgurl = value.headimgurl;
        this.createtime = value.createtime;
    }

    public Clicklike(
        Integer   id,
        Integer   galleryid,
        Integer   detailid,
        Integer   userid,
        String    openid,
        String    nickname,
        String    headimgurl,
        Timestamp createtime
    ) {
        this.id = id;
        this.galleryid = galleryid;
        this.detailid = detailid;
        this.userid = userid;
        this.openid = openid;
        this.nickname = nickname;
        this.headimgurl = headimgurl;
        this.createtime = createtime;
    }

    public Integer getId() {
        return this.id;
    }

    public Clicklike setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getGalleryid() {
        return this.galleryid;
    }

    public Clicklike setGalleryid(Integer galleryid) {
        this.galleryid = galleryid;
        return this;
    }

    public Integer getDetailid() {
        return this.detailid;
    }

    public Clicklike setDetailid(Integer detailid) {
        this.detailid = detailid;
        return this;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public Clicklike setUserid(Integer userid) {
        this.userid = userid;
        return this;
    }

    public String getOpenid() {
        return this.openid;
    }

    public Clicklike setOpenid(String openid) {
        this.openid = openid;
        return this;
    }

    public String getNickname() {
        return this.nickname;
    }

    public Clicklike setNickname(String nickname) {
        this.nickname = nickname;
        return this;
    }

    public String getHeadimgurl() {
        return this.headimgurl;
    }

    public Clicklike setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
        return this;
    }

    public Timestamp getCreatetime() {
        return this.createtime;
    }

    public Clicklike setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Clicklike (");

        sb.append(id);
        sb.append(", ").append(galleryid);
        sb.append(", ").append(detailid);
        sb.append(", ").append(userid);
        sb.append(", ").append(openid);
        sb.append(", ").append(nickname);
        sb.append(", ").append(headimgurl);
        sb.append(", ").append(createtime);

        sb.append(")");
        return sb.toString();
    }
}
