/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.tools.dashboard.myspace.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Complain implements Serializable {

    private static final long serialVersionUID = 1002760282;

    private Integer   id;
    private Integer   galleryid;
    private Integer   userid;
    private String    content;
    private Timestamp createtime;

    public Complain() {}

    public Complain(Complain value) {
        this.id = value.id;
        this.galleryid = value.galleryid;
        this.userid = value.userid;
        this.content = value.content;
        this.createtime = value.createtime;
    }

    public Complain(
        Integer   id,
        Integer   galleryid,
        Integer   userid,
        String    content,
        Timestamp createtime
    ) {
        this.id = id;
        this.galleryid = galleryid;
        this.userid = userid;
        this.content = content;
        this.createtime = createtime;
    }

    public Integer getId() {
        return this.id;
    }

    public Complain setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getGalleryid() {
        return this.galleryid;
    }

    public Complain setGalleryid(Integer galleryid) {
        this.galleryid = galleryid;
        return this;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public Complain setUserid(Integer userid) {
        this.userid = userid;
        return this;
    }

    public String getContent() {
        return this.content;
    }

    public Complain setContent(String content) {
        this.content = content;
        return this;
    }

    public Timestamp getCreatetime() {
        return this.createtime;
    }

    public Complain setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Complain (");

        sb.append(id);
        sb.append(", ").append(galleryid);
        sb.append(", ").append(userid);
        sb.append(", ").append(content);
        sb.append(", ").append(createtime);

        sb.append(")");
        return sb.toString();
    }
}
