/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.tools.dashboard.myspace.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gallery implements Serializable {

    private static final long serialVersionUID = 1124972437;

    private Integer   id;
    private String    openid;
    private String    ada;
    private Integer   attachmentid;
    private String    choosemusic;
    private String    galleryname;
    private String    description;
    private Integer   status;
    private String    qrcodekey;
    private Timestamp createtime;
    private Integer   creatorid;
    private Timestamp updatetime;
    private Integer   modifierid;

    public Gallery() {}

    public Gallery(Gallery value) {
        this.id = value.id;
        this.openid = value.openid;
        this.ada = value.ada;
        this.attachmentid = value.attachmentid;
        this.choosemusic = value.choosemusic;
        this.galleryname = value.galleryname;
        this.description = value.description;
        this.status = value.status;
        this.qrcodekey = value.qrcodekey;
        this.createtime = value.createtime;
        this.creatorid = value.creatorid;
        this.updatetime = value.updatetime;
        this.modifierid = value.modifierid;
    }

    public Gallery(
        Integer   id,
        String    openid,
        String    ada,
        Integer   attachmentid,
        String    choosemusic,
        String    galleryname,
        String    description,
        Integer   status,
        String    qrcodekey,
        Timestamp createtime,
        Integer   creatorid,
        Timestamp updatetime,
        Integer   modifierid
    ) {
        this.id = id;
        this.openid = openid;
        this.ada = ada;
        this.attachmentid = attachmentid;
        this.choosemusic = choosemusic;
        this.galleryname = galleryname;
        this.description = description;
        this.status = status;
        this.qrcodekey = qrcodekey;
        this.createtime = createtime;
        this.creatorid = creatorid;
        this.updatetime = updatetime;
        this.modifierid = modifierid;
    }

    public Integer getId() {
        return this.id;
    }

    public Gallery setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getOpenid() {
        return this.openid;
    }

    public Gallery setOpenid(String openid) {
        this.openid = openid;
        return this;
    }

    public String getAda() {
        return this.ada;
    }

    public Gallery setAda(String ada) {
        this.ada = ada;
        return this;
    }

    public Integer getAttachmentid() {
        return this.attachmentid;
    }

    public Gallery setAttachmentid(Integer attachmentid) {
        this.attachmentid = attachmentid;
        return this;
    }

    public String getChoosemusic() {
        return this.choosemusic;
    }

    public Gallery setChoosemusic(String choosemusic) {
        this.choosemusic = choosemusic;
        return this;
    }

    public String getGalleryname() {
        return this.galleryname;
    }

    public Gallery setGalleryname(String galleryname) {
        this.galleryname = galleryname;
        return this;
    }

    public String getDescription() {
        return this.description;
    }

    public Gallery setDescription(String description) {
        this.description = description;
        return this;
    }

    public Integer getStatus() {
        return this.status;
    }

    public Gallery setStatus(Integer status) {
        this.status = status;
        return this;
    }

    public String getQrcodekey() {
        return this.qrcodekey;
    }

    public Gallery setQrcodekey(String qrcodekey) {
        this.qrcodekey = qrcodekey;
        return this;
    }

    public Timestamp getCreatetime() {
        return this.createtime;
    }

    public Gallery setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
        return this;
    }

    public Integer getCreatorid() {
        return this.creatorid;
    }

    public Gallery setCreatorid(Integer creatorid) {
        this.creatorid = creatorid;
        return this;
    }

    public Timestamp getUpdatetime() {
        return this.updatetime;
    }

    public Gallery setUpdatetime(Timestamp updatetime) {
        this.updatetime = updatetime;
        return this;
    }

    public Integer getModifierid() {
        return this.modifierid;
    }

    public Gallery setModifierid(Integer modifierid) {
        this.modifierid = modifierid;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Gallery (");

        sb.append(id);
        sb.append(", ").append(openid);
        sb.append(", ").append(ada);
        sb.append(", ").append(attachmentid);
        sb.append(", ").append(choosemusic);
        sb.append(", ").append(galleryname);
        sb.append(", ").append(description);
        sb.append(", ").append(status);
        sb.append(", ").append(qrcodekey);
        sb.append(", ").append(createtime);
        sb.append(", ").append(creatorid);
        sb.append(", ").append(updatetime);
        sb.append(", ").append(modifierid);

        sb.append(")");
        return sb.toString();
    }
}
