/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Campaign;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.CampaignRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CampaignDao extends DAOImpl<CampaignRecord, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign, Integer> {

    /**
     * Create a new CampaignDao without any configuration
     */
    public CampaignDao() {
        super(Campaign.CAMPAIGN, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign.class);
    }

    /**
     * Create a new CampaignDao with an attached configuration
     */
    public CampaignDao(Configuration configuration) {
        super(Campaign.CAMPAIGN, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchById(Integer... values) {
        return fetch(Campaign.CAMPAIGN.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign fetchOneById(Integer value) {
        return fetchOne(Campaign.CAMPAIGN.ID, value);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByTitle(String... values) {
        return fetch(Campaign.CAMPAIGN.TITLE, values);
    }

    /**
     * Fetch records that have <code>location IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByLocation(String... values) {
        return fetch(Campaign.CAMPAIGN.LOCATION, values);
    }

    /**
     * Fetch records that have <code>digest IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByDigest(String... values) {
        return fetch(Campaign.CAMPAIGN.DIGEST, values);
    }

    /**
     * Fetch records that have <code>applyDeadline IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByApplydeadline(LocalDateTime... values) {
        return fetch(Campaign.CAMPAIGN.APPLYDEADLINE, values);
    }

    /**
     * Fetch records that have <code>startTime IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByStarttime(LocalDateTime... values) {
        return fetch(Campaign.CAMPAIGN.STARTTIME, values);
    }

    /**
     * Fetch records that have <code>endTime IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByEndtime(LocalDateTime... values) {
        return fetch(Campaign.CAMPAIGN.ENDTIME, values);
    }

    /**
     * Fetch records that have <code>limit IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByLimit(Integer... values) {
        return fetch(Campaign.CAMPAIGN.LIMIT, values);
    }

    /**
     * Fetch records that have <code>coverImageKey IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByCoverimagekey(String... values) {
        return fetch(Campaign.CAMPAIGN.COVERIMAGEKEY, values);
    }

    /**
     * Fetch records that have <code>chargeImageKey IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByChargeimagekey(String... values) {
        return fetch(Campaign.CAMPAIGN.CHARGEIMAGEKEY, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByContent(String... values) {
        return fetch(Campaign.CAMPAIGN.CONTENT, values);
    }

    /**
     * Fetch records that have <code>canCoverWorkshop IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByCancoverworkshop(Integer... values) {
        return fetch(Campaign.CAMPAIGN.CANCOVERWORKSHOP, values);
    }

    /**
     * Fetch records that have <code>isCharge IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByIscharge(Integer... values) {
        return fetch(Campaign.CAMPAIGN.ISCHARGE, values);
    }

    /**
     * Fetch records that have <code>templateId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByTemplateid(Integer... values) {
        return fetch(Campaign.CAMPAIGN.TEMPLATEID, values);
    }

    /**
     * Fetch records that have <code>ada IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByAda(String... values) {
        return fetch(Campaign.CAMPAIGN.ADA, values);
    }

    /**
     * Fetch records that have <code>workshopUrl IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByWorkshopurl(String... values) {
        return fetch(Campaign.CAMPAIGN.WORKSHOPURL, values);
    }

    /**
     * Fetch records that have <code>workshopName IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByWorkshopname(String... values) {
        return fetch(Campaign.CAMPAIGN.WORKSHOPNAME, values);
    }

    /**
     * Fetch records that have <code>workshopHeadImgUrl IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByWorkshopheadimgurl(String... values) {
        return fetch(Campaign.CAMPAIGN.WORKSHOPHEADIMGURL, values);
    }

    /**
     * Fetch records that have <code>workshopWelcomeWord IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByWorkshopwelcomeword(String... values) {
        return fetch(Campaign.CAMPAIGN.WORKSHOPWELCOMEWORD, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByStatus(Integer... values) {
        return fetch(Campaign.CAMPAIGN.STATUS, values);
    }

    /**
     * Fetch records that have <code>createUserId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByCreateuserid(Integer... values) {
        return fetch(Campaign.CAMPAIGN.CREATEUSERID, values);
    }

    /**
     * Fetch records that have <code>createTime IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByCreatetime(LocalDateTime... values) {
        return fetch(Campaign.CAMPAIGN.CREATETIME, values);
    }

    /**
     * Fetch records that have <code>shareDigest IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchBySharedigest(String... values) {
        return fetch(Campaign.CAMPAIGN.SHAREDIGEST, values);
    }

    /**
     * Fetch records that have <code>organizers IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByOrganizers(String... values) {
        return fetch(Campaign.CAMPAIGN.ORGANIZERS, values);
    }

    /**
     * Fetch records that have <code>ticket IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Campaign> fetchByTicket(String... values) {
        return fetch(Campaign.CAMPAIGN.TICKET, values);
    }
}
