/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Connection;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.ConnectionRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConnectionDao extends DAOImpl<ConnectionRecord, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Connection, Integer> {

    /**
     * Create a new ConnectionDao without any configuration
     */
    public ConnectionDao() {
        super(Connection.CONNECTION, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Connection.class);
    }

    /**
     * Create a new ConnectionDao with an attached configuration
     */
    public ConnectionDao(Configuration configuration) {
        super(Connection.CONNECTION, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Connection.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Connection object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Connection> fetchById(Integer... values) {
        return fetch(Connection.CONNECTION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Connection fetchOneById(Integer value) {
        return fetchOne(Connection.CONNECTION.ID, value);
    }

    /**
     * Fetch records that have <code>userId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Connection> fetchByUserid(Integer... values) {
        return fetch(Connection.CONNECTION.USERID, values);
    }

    /**
     * Fetch records that have <code>shareId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Connection> fetchByShareid(Integer... values) {
        return fetch(Connection.CONNECTION.SHAREID, values);
    }

    /**
     * Fetch records that have <code>campaignId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Connection> fetchByCampaignid(Integer... values) {
        return fetch(Connection.CONNECTION.CAMPAIGNID, values);
    }

    /**
     * Fetch records that have <code>createType IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Connection> fetchByCreatetype(String... values) {
        return fetch(Connection.CONNECTION.CREATETYPE, values);
    }

    /**
     * Fetch records that have <code>createTime IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Connection> fetchByCreatetime(LocalDateTime... values) {
        return fetch(Connection.CONNECTION.CREATETIME, values);
    }
}
