/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Register;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.RegisterRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegisterDao extends DAOImpl<RegisterRecord, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Register, Integer> {

    /**
     * Create a new RegisterDao without any configuration
     */
    public RegisterDao() {
        super(Register.REGISTER, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Register.class);
    }

    /**
     * Create a new RegisterDao with an attached configuration
     */
    public RegisterDao(Configuration configuration) {
        super(Register.REGISTER, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Register.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Register object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Register> fetchById(Integer... values) {
        return fetch(Register.REGISTER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Register fetchOneById(Integer value) {
        return fetchOne(Register.REGISTER.ID, value);
    }

    /**
     * Fetch records that have <code>campaignId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Register> fetchByCampaignid(Integer... values) {
        return fetch(Register.REGISTER.CAMPAIGNID, values);
    }

    /**
     * Fetch records that have <code>userId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Register> fetchByUserid(Integer... values) {
        return fetch(Register.REGISTER.USERID, values);
    }

    /**
     * Fetch records that have <code>createTime IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Register> fetchByCreatetime(LocalDateTime... values) {
        return fetch(Register.REGISTER.CREATETIME, values);
    }

    /**
     * Fetch records that have <code>hasApply IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Register> fetchByHasapply(Integer... values) {
        return fetch(Register.REGISTER.HASAPPLY, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Register> fetchByStatus(Integer... values) {
        return fetch(Register.REGISTER.STATUS, values);
    }
}
