/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Report;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.ReportRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportDao extends DAOImpl<ReportRecord, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Report, Integer> {

    /**
     * Create a new ReportDao without any configuration
     */
    public ReportDao() {
        super(Report.REPORT, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Report.class);
    }

    /**
     * Create a new ReportDao with an attached configuration
     */
    public ReportDao(Configuration configuration) {
        super(Report.REPORT, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Report.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Report object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Report> fetchById(Integer... values) {
        return fetch(Report.REPORT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Report fetchOneById(Integer value) {
        return fetchOne(Report.REPORT.ID, value);
    }

    /**
     * Fetch records that have <code>campaignId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Report> fetchByCampaignid(Integer... values) {
        return fetch(Report.REPORT.CAMPAIGNID, values);
    }

    /**
     * Fetch records that have <code>userId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Report> fetchByUserid(Integer... values) {
        return fetch(Report.REPORT.USERID, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Report> fetchByContent(String... values) {
        return fetch(Report.REPORT.CONTENT, values);
    }

    /**
     * Fetch records that have <code>createTime IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Report> fetchByCreatetime(LocalDateTime... values) {
        return fetch(Report.REPORT.CREATETIME, values);
    }
}
