/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Share;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.ShareRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShareDao extends DAOImpl<ShareRecord, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share, Integer> {

    /**
     * Create a new ShareDao without any configuration
     */
    public ShareDao() {
        super(Share.SHARE, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share.class);
    }

    /**
     * Create a new ShareDao with an attached configuration
     */
    public ShareDao(Configuration configuration) {
        super(Share.SHARE, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchById(Integer... values) {
        return fetch(Share.SHARE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share fetchOneById(Integer value) {
        return fetchOne(Share.SHARE.ID, value);
    }

    /**
     * Fetch records that have <code>userId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByUserid(Integer... values) {
        return fetch(Share.SHARE.USERID, values);
    }

    /**
     * Fetch records that have <code>userType IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByUsertype(Integer... values) {
        return fetch(Share.SHARE.USERTYPE, values);
    }

    /**
     * Fetch records that have <code>scene IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByScene(String... values) {
        return fetch(Share.SHARE.SCENE, values);
    }

    /**
     * Fetch records that have <code>handlerUserId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByHandleruserid(Integer... values) {
        return fetch(Share.SHARE.HANDLERUSERID, values);
    }

    /**
     * Fetch records that have <code>handlerShareId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByHandlershareid(Integer... values) {
        return fetch(Share.SHARE.HANDLERSHAREID, values);
    }

    /**
     * Fetch records that have <code>beforeShareId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByBeforeshareid(Integer... values) {
        return fetch(Share.SHARE.BEFORESHAREID, values);
    }

    /**
     * Fetch records that have <code>isCoverWorkshop IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByIscoverworkshop(Integer... values) {
        return fetch(Share.SHARE.ISCOVERWORKSHOP, values);
    }

    /**
     * Fetch records that have <code>inviteUserId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByInviteuserid(Integer... values) {
        return fetch(Share.SHARE.INVITEUSERID, values);
    }

    /**
     * Fetch records that have <code>inviteCode IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByInvitecode(String... values) {
        return fetch(Share.SHARE.INVITECODE, values);
    }

    /**
     * Fetch records that have <code>ada IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByAda(String... values) {
        return fetch(Share.SHARE.ADA, values);
    }

    /**
     * Fetch records that have <code>workshopUrl IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByWorkshopurl(String... values) {
        return fetch(Share.SHARE.WORKSHOPURL, values);
    }

    /**
     * Fetch records that have <code>workshopName IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByWorkshopname(String... values) {
        return fetch(Share.SHARE.WORKSHOPNAME, values);
    }

    /**
     * Fetch records that have <code>workshopHeadImgUrl IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByWorkshopheadimgurl(String... values) {
        return fetch(Share.SHARE.WORKSHOPHEADIMGURL, values);
    }

    /**
     * Fetch records that have <code>workshopWelcomeWord IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByWorkshopwelcomeword(String... values) {
        return fetch(Share.SHARE.WORKSHOPWELCOMEWORD, values);
    }

    /**
     * Fetch records that have <code>campaignIds IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByCampaignids(String... values) {
        return fetch(Share.SHARE.CAMPAIGNIDS, values);
    }

    /**
     * Fetch records that have <code>shareTitle IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchBySharetitle(String... values) {
        return fetch(Share.SHARE.SHARETITLE, values);
    }

    /**
     * Fetch records that have <code>shareDigest IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchBySharedigest(String... values) {
        return fetch(Share.SHARE.SHAREDIGEST, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByStatus(Integer... values) {
        return fetch(Share.SHARE.STATUS, values);
    }

    /**
     * Fetch records that have <code>initialUserId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByInitialuserid(Integer... values) {
        return fetch(Share.SHARE.INITIALUSERID, values);
    }

    /**
     * Fetch records that have <code>createTime IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Share> fetchByCreatetime(LocalDateTime... values) {
        return fetch(Share.SHARE.CREATETIME, values);
    }
}
