/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Userinfo;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.UserinfoRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserinfoDao extends DAOImpl<UserinfoRecord, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Userinfo, Integer> {

    /**
     * Create a new UserinfoDao without any configuration
     */
    public UserinfoDao() {
        super(Userinfo.USERINFO, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Userinfo.class);
    }

    /**
     * Create a new UserinfoDao with an attached configuration
     */
    public UserinfoDao(Configuration configuration) {
        super(Userinfo.USERINFO, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Userinfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Userinfo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Userinfo> fetchById(Integer... values) {
        return fetch(Userinfo.USERINFO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Userinfo fetchOneById(Integer value) {
        return fetchOne(Userinfo.USERINFO.ID, value);
    }

    /**
     * Fetch records that have <code>userId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Userinfo> fetchByUserid(Integer... values) {
        return fetch(Userinfo.USERINFO.USERID, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Userinfo> fetchByName(String... values) {
        return fetch(Userinfo.USERINFO.NAME, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Userinfo> fetchByPhone(String... values) {
        return fetch(Userinfo.USERINFO.PHONE, values);
    }

    /**
     * Fetch records that have <code>createTime IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.Userinfo> fetchByCreatetime(LocalDateTime... values) {
        return fetch(Userinfo.USERINFO.CREATETIME, values);
    }
}
