/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.User;
import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records.UserRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.User, Integer> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.User> fetchById(Integer... values) {
        return fetch(User.USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.User fetchOneById(Integer value) {
        return fetchOne(User.USER.ID, value);
    }

    /**
     * Fetch records that have <code>isAbo IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.User> fetchByIsabo(Integer... values) {
        return fetch(User.USER.ISABO, values);
    }

    /**
     * Fetch records that have <code>openId IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.User> fetchByOpenid(String... values) {
        return fetch(User.USER.OPENID, values);
    }

    /**
     * Fetch records that have <code>nickName IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.User> fetchByNickname(String... values) {
        return fetch(User.USER.NICKNAME, values);
    }

    /**
     * Fetch records that have <code>headImgUrl IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.User> fetchByHeadimgurl(String... values) {
        return fetch(User.USER.HEADIMGURL, values);
    }

    /**
     * Fetch records that have <code>createTime IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.User> fetchByCreatetime(LocalDateTime... values) {
        return fetch(User.USER.CREATETIME, values);
    }

    /**
     * Fetch records that have <code>inviteCode IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.User> fetchByInvitecode(String... values) {
        return fetch(User.USER.INVITECODE, values);
    }

    /**
     * Fetch records that have <code>ada IN (values)</code>
     */
    public List<org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.pojos.User> fetchByAda(String... values) {
        return fetch(User.USER.ADA, values);
    }
}
