/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Apply;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplyRecord extends UpdatableRecordImpl<ApplyRecord> implements Record7<Integer, Integer, Integer, Integer, String, LocalDateTime, Integer> {

    private static final long serialVersionUID = 2001411115;

    /**
     * Setter for <code>aatool.apply.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>aatool.apply.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>aatool.apply.shareId</code>.
     */
    public void setShareid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>aatool.apply.shareId</code>.
     */
    public Integer getShareid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>aatool.apply.campaignId</code>.
     */
    public void setCampaignid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>aatool.apply.campaignId</code>.
     */
    public Integer getCampaignid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>aatool.apply.userId</code>.
     */
    public void setUserid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>aatool.apply.userId</code>.
     */
    public Integer getUserid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>aatool.apply.memo</code>.
     */
    public void setMemo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>aatool.apply.memo</code>.
     */
    public String getMemo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>aatool.apply.createTime</code>.
     */
    public void setCreatetime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>aatool.apply.createTime</code>.
     */
    public LocalDateTime getCreatetime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>aatool.apply.status</code>.
     */
    public void setStatus(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>aatool.apply.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, String, LocalDateTime, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, String, LocalDateTime, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Apply.APPLY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Apply.APPLY.SHAREID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Apply.APPLY.CAMPAIGNID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Apply.APPLY.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Apply.APPLY.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return Apply.APPLY.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Apply.APPLY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getShareid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCampaignid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyRecord value2(Integer value) {
        setShareid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyRecord value3(Integer value) {
        setCampaignid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyRecord value4(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyRecord value5(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyRecord value6(LocalDateTime value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyRecord value7(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, LocalDateTime value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplyRecord
     */
    public ApplyRecord() {
        super(Apply.APPLY);
    }

    /**
     * Create a detached, initialised ApplyRecord
     */
    public ApplyRecord(Integer id, Integer shareid, Integer campaignid, Integer userid, String memo, LocalDateTime createtime, Integer status) {
        super(Apply.APPLY);

        set(0, id);
        set(1, shareid);
        set(2, campaignid);
        set(3, userid);
        set(4, memo);
        set(5, createtime);
        set(6, status);
    }
}
