/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.AreaActivityRegistrationForm;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AreaActivityRegistrationFormRecord extends UpdatableRecordImpl<AreaActivityRegistrationFormRecord> implements Record6<Integer, Integer, Integer, String, String, LocalDateTime> {

    private static final long serialVersionUID = -1673699949;

    /**
     * Setter for <code>aatool.area_activity_registration_form.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>aatool.area_activity_registration_form.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>aatool.area_activity_registration_form.batchId</code>.
     */
    public void setBatchid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>aatool.area_activity_registration_form.batchId</code>.
     */
    public Integer getBatchid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>aatool.area_activity_registration_form.userId</code>.
     */
    public void setUserid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>aatool.area_activity_registration_form.userId</code>.
     */
    public Integer getUserid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>aatool.area_activity_registration_form.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>aatool.area_activity_registration_form.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>aatool.area_activity_registration_form.ada</code>.
     */
    public void setAda(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>aatool.area_activity_registration_form.ada</code>.
     */
    public String getAda() {
        return (String) get(4);
    }

    /**
     * Setter for <code>aatool.area_activity_registration_form.createTime</code>.
     */
    public void setCreatetime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>aatool.area_activity_registration_form.createTime</code>.
     */
    public LocalDateTime getCreatetime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, String, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, String, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM.BATCHID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM.ADA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getBatchid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAda();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaActivityRegistrationFormRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaActivityRegistrationFormRecord value2(Integer value) {
        setBatchid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaActivityRegistrationFormRecord value3(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaActivityRegistrationFormRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaActivityRegistrationFormRecord value5(String value) {
        setAda(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaActivityRegistrationFormRecord value6(LocalDateTime value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaActivityRegistrationFormRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AreaActivityRegistrationFormRecord
     */
    public AreaActivityRegistrationFormRecord() {
        super(AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM);
    }

    /**
     * Create a detached, initialised AreaActivityRegistrationFormRecord
     */
    public AreaActivityRegistrationFormRecord(Integer id, Integer batchid, Integer userid, String name, String ada, LocalDateTime createtime) {
        super(AreaActivityRegistrationForm.AREA_ACTIVITY_REGISTRATION_FORM);

        set(0, id);
        set(1, batchid);
        set(2, userid);
        set(3, name);
        set(4, ada);
        set(5, createtime);
    }
}
