/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Campaign;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CampaignRecord extends UpdatableRecordImpl<CampaignRecord> {

    private static final long serialVersionUID = -1088529778;

    /**
     * Setter for <code>aatool.campaign.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>aatool.campaign.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>aatool.campaign.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>aatool.campaign.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>aatool.campaign.location</code>.
     */
    public void setLocation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>aatool.campaign.location</code>.
     */
    public String getLocation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>aatool.campaign.digest</code>.
     */
    public void setDigest(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>aatool.campaign.digest</code>.
     */
    public String getDigest() {
        return (String) get(3);
    }

    /**
     * Setter for <code>aatool.campaign.applyDeadline</code>.
     */
    public void setApplydeadline(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>aatool.campaign.applyDeadline</code>.
     */
    public LocalDateTime getApplydeadline() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>aatool.campaign.startTime</code>.
     */
    public void setStarttime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>aatool.campaign.startTime</code>.
     */
    public LocalDateTime getStarttime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>aatool.campaign.endTime</code>.
     */
    public void setEndtime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>aatool.campaign.endTime</code>.
     */
    public LocalDateTime getEndtime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>aatool.campaign.limit</code>.
     */
    public void setLimit(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>aatool.campaign.limit</code>.
     */
    public Integer getLimit() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>aatool.campaign.coverImageKey</code>.
     */
    public void setCoverimagekey(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>aatool.campaign.coverImageKey</code>.
     */
    public String getCoverimagekey() {
        return (String) get(8);
    }

    /**
     * Setter for <code>aatool.campaign.chargeImageKey</code>.
     */
    public void setChargeimagekey(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>aatool.campaign.chargeImageKey</code>.
     */
    public String getChargeimagekey() {
        return (String) get(9);
    }

    /**
     * Setter for <code>aatool.campaign.content</code>.
     */
    public void setContent(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>aatool.campaign.content</code>.
     */
    public String getContent() {
        return (String) get(10);
    }

    /**
     * Setter for <code>aatool.campaign.canCoverWorkshop</code>.
     */
    public void setCancoverworkshop(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>aatool.campaign.canCoverWorkshop</code>.
     */
    public Integer getCancoverworkshop() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>aatool.campaign.isCharge</code>.
     */
    public void setIscharge(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>aatool.campaign.isCharge</code>.
     */
    public Integer getIscharge() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>aatool.campaign.templateId</code>.
     */
    public void setTemplateid(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>aatool.campaign.templateId</code>.
     */
    public Integer getTemplateid() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>aatool.campaign.ada</code>.
     */
    public void setAda(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>aatool.campaign.ada</code>.
     */
    public String getAda() {
        return (String) get(14);
    }

    /**
     * Setter for <code>aatool.campaign.workshopUrl</code>.
     */
    public void setWorkshopurl(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>aatool.campaign.workshopUrl</code>.
     */
    public String getWorkshopurl() {
        return (String) get(15);
    }

    /**
     * Setter for <code>aatool.campaign.workshopName</code>.
     */
    public void setWorkshopname(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>aatool.campaign.workshopName</code>.
     */
    public String getWorkshopname() {
        return (String) get(16);
    }

    /**
     * Setter for <code>aatool.campaign.workshopHeadImgUrl</code>.
     */
    public void setWorkshopheadimgurl(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>aatool.campaign.workshopHeadImgUrl</code>.
     */
    public String getWorkshopheadimgurl() {
        return (String) get(17);
    }

    /**
     * Setter for <code>aatool.campaign.workshopWelcomeWord</code>.
     */
    public void setWorkshopwelcomeword(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>aatool.campaign.workshopWelcomeWord</code>.
     */
    public String getWorkshopwelcomeword() {
        return (String) get(18);
    }

    /**
     * Setter for <code>aatool.campaign.status</code>.
     */
    public void setStatus(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>aatool.campaign.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>aatool.campaign.createUserId</code>.
     */
    public void setCreateuserid(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>aatool.campaign.createUserId</code>.
     */
    public Integer getCreateuserid() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>aatool.campaign.createTime</code>.
     */
    public void setCreatetime(LocalDateTime value) {
        set(21, value);
    }

    /**
     * Getter for <code>aatool.campaign.createTime</code>.
     */
    public LocalDateTime getCreatetime() {
        return (LocalDateTime) get(21);
    }

    /**
     * Setter for <code>aatool.campaign.shareDigest</code>.
     */
    public void setSharedigest(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>aatool.campaign.shareDigest</code>.
     */
    public String getSharedigest() {
        return (String) get(22);
    }

    /**
     * Setter for <code>aatool.campaign.organizers</code>.
     */
    public void setOrganizers(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>aatool.campaign.organizers</code>.
     */
    public String getOrganizers() {
        return (String) get(23);
    }

    /**
     * Setter for <code>aatool.campaign.ticket</code>.
     */
    public void setTicket(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>aatool.campaign.ticket</code>.
     */
    public String getTicket() {
        return (String) get(24);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CampaignRecord
     */
    public CampaignRecord() {
        super(Campaign.CAMPAIGN);
    }

    /**
     * Create a detached, initialised CampaignRecord
     */
    public CampaignRecord(Integer id, String title, String location, String digest, LocalDateTime applydeadline, LocalDateTime starttime, LocalDateTime endtime, Integer limit, String coverimagekey, String chargeimagekey, String content, Integer cancoverworkshop, Integer ischarge, Integer templateid, String ada, String workshopurl, String workshopname, String workshopheadimgurl, String workshopwelcomeword, Integer status, Integer createuserid, LocalDateTime createtime, String sharedigest, String organizers, String ticket) {
        super(Campaign.CAMPAIGN);

        set(0, id);
        set(1, title);
        set(2, location);
        set(3, digest);
        set(4, applydeadline);
        set(5, starttime);
        set(6, endtime);
        set(7, limit);
        set(8, coverimagekey);
        set(9, chargeimagekey);
        set(10, content);
        set(11, cancoverworkshop);
        set(12, ischarge);
        set(13, templateid);
        set(14, ada);
        set(15, workshopurl);
        set(16, workshopname);
        set(17, workshopheadimgurl);
        set(18, workshopwelcomeword);
        set(19, status);
        set(20, createuserid);
        set(21, createtime);
        set(22, sharedigest);
        set(23, organizers);
        set(24, ticket);
    }
}
