/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Connection;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConnectionRecord extends UpdatableRecordImpl<ConnectionRecord> implements Record6<Integer, Integer, Integer, Integer, String, LocalDateTime> {

    private static final long serialVersionUID = 411412651;

    /**
     * Setter for <code>aatool.connection.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>aatool.connection.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>aatool.connection.userId</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>aatool.connection.userId</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>aatool.connection.shareId</code>.
     */
    public void setShareid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>aatool.connection.shareId</code>.
     */
    public Integer getShareid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>aatool.connection.campaignId</code>.
     */
    public void setCampaignid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>aatool.connection.campaignId</code>.
     */
    public Integer getCampaignid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>aatool.connection.createType</code>.
     */
    public void setCreatetype(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>aatool.connection.createType</code>.
     */
    public String getCreatetype() {
        return (String) get(4);
    }

    /**
     * Setter for <code>aatool.connection.createTime</code>.
     */
    public void setCreatetime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>aatool.connection.createTime</code>.
     */
    public LocalDateTime getCreatetime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, String, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, String, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Connection.CONNECTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Connection.CONNECTION.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Connection.CONNECTION.SHAREID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Connection.CONNECTION.CAMPAIGNID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Connection.CONNECTION.CREATETYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return Connection.CONNECTION.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getShareid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCampaignid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreatetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectionRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectionRecord value3(Integer value) {
        setShareid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectionRecord value4(Integer value) {
        setCampaignid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectionRecord value5(String value) {
        setCreatetype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectionRecord value6(LocalDateTime value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectionRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConnectionRecord
     */
    public ConnectionRecord() {
        super(Connection.CONNECTION);
    }

    /**
     * Create a detached, initialised ConnectionRecord
     */
    public ConnectionRecord(Integer id, Integer userid, Integer shareid, Integer campaignid, String createtype, LocalDateTime createtime) {
        super(Connection.CONNECTION);

        set(0, id);
        set(1, userid);
        set(2, shareid);
        set(3, campaignid);
        set(4, createtype);
        set(5, createtime);
    }
}
