/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.codeworks.web.toolsdashboardaatool.jooq.aatool.tables.Template;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TemplateRecord extends UpdatableRecordImpl<TemplateRecord> implements Record17<Integer, String, Integer, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, String, String, String, Integer, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = -1091789505;

    /**
     * Setter for <code>aatool.template.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>aatool.template.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>aatool.template.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>aatool.template.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>aatool.template.sequence</code>.
     */
    public void setSequence(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>aatool.template.sequence</code>.
     */
    public Integer getSequence() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>aatool.template.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>aatool.template.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>aatool.template.location</code>.
     */
    public void setLocation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>aatool.template.location</code>.
     */
    public String getLocation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>aatool.template.digest</code>.
     */
    public void setDigest(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>aatool.template.digest</code>.
     */
    public String getDigest() {
        return (String) get(5);
    }

    /**
     * Setter for <code>aatool.template.applyDeadline</code>.
     */
    public void setApplydeadline(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>aatool.template.applyDeadline</code>.
     */
    public LocalDateTime getApplydeadline() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>aatool.template.startTime</code>.
     */
    public void setStarttime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>aatool.template.startTime</code>.
     */
    public LocalDateTime getStarttime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>aatool.template.endTime</code>.
     */
    public void setEndtime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>aatool.template.endTime</code>.
     */
    public LocalDateTime getEndtime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>aatool.template.limit</code>.
     */
    public void setLimit(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>aatool.template.limit</code>.
     */
    public Integer getLimit() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>aatool.template.coverImageKey</code>.
     */
    public void setCoverimagekey(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>aatool.template.coverImageKey</code>.
     */
    public String getCoverimagekey() {
        return (String) get(10);
    }

    /**
     * Setter for <code>aatool.template.chargeImageKey</code>.
     */
    public void setChargeimagekey(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>aatool.template.chargeImageKey</code>.
     */
    public String getChargeimagekey() {
        return (String) get(11);
    }

    /**
     * Setter for <code>aatool.template.content</code>.
     */
    public void setContent(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>aatool.template.content</code>.
     */
    public String getContent() {
        return (String) get(12);
    }

    /**
     * Setter for <code>aatool.template.canCoverWorkshop</code>.
     */
    public void setCancoverworkshop(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>aatool.template.canCoverWorkshop</code>.
     */
    public Integer getCancoverworkshop() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>aatool.template.isCharge</code>.
     */
    public void setIscharge(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>aatool.template.isCharge</code>.
     */
    public Integer getIscharge() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>aatool.template.status</code>.
     */
    public void setStatus(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>aatool.template.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>aatool.template.createTime</code>.
     */
    public void setCreatetime(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>aatool.template.createTime</code>.
     */
    public LocalDateTime getCreatetime() {
        return (LocalDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, Integer, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, String, String, String, Integer, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, Integer, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, String, String, String, Integer, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Template.TEMPLATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Template.TEMPLATE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Template.TEMPLATE.SEQUENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Template.TEMPLATE.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Template.TEMPLATE.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Template.TEMPLATE.DIGEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return Template.TEMPLATE.APPLYDEADLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return Template.TEMPLATE.STARTTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return Template.TEMPLATE.ENDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Template.TEMPLATE.LIMIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Template.TEMPLATE.COVERIMAGEKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Template.TEMPLATE.CHARGEIMAGEKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Template.TEMPLATE.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return Template.TEMPLATE.CANCOVERWORKSHOP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return Template.TEMPLATE.ISCHARGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return Template.TEMPLATE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field17() {
        return Template.TEMPLATE.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSequence();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDigest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getApplydeadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getStarttime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getEndtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getLimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCoverimagekey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getChargeimagekey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getCancoverworkshop();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getIscharge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value17() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value3(Integer value) {
        setSequence(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value4(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value5(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value6(String value) {
        setDigest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value7(LocalDateTime value) {
        setApplydeadline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value8(LocalDateTime value) {
        setStarttime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value9(LocalDateTime value) {
        setEndtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value10(Integer value) {
        setLimit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value11(String value) {
        setCoverimagekey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value12(String value) {
        setChargeimagekey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value13(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value14(Integer value) {
        setCancoverworkshop(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value15(Integer value) {
        setIscharge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value16(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord value17(LocalDateTime value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TemplateRecord values(Integer value1, String value2, Integer value3, String value4, String value5, String value6, LocalDateTime value7, LocalDateTime value8, LocalDateTime value9, Integer value10, String value11, String value12, String value13, Integer value14, Integer value15, Integer value16, LocalDateTime value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TemplateRecord
     */
    public TemplateRecord() {
        super(Template.TEMPLATE);
    }

    /**
     * Create a detached, initialised TemplateRecord
     */
    public TemplateRecord(Integer id, String name, Integer sequence, String title, String location, String digest, LocalDateTime applydeadline, LocalDateTime starttime, LocalDateTime endtime, Integer limit, String coverimagekey, String chargeimagekey, String content, Integer cancoverworkshop, Integer ischarge, Integer status, LocalDateTime createtime) {
        super(Template.TEMPLATE);

        set(0, id);
        set(1, name);
        set(2, sequence);
        set(3, title);
        set(4, location);
        set(5, digest);
        set(6, applydeadline);
        set(7, starttime);
        set(8, endtime);
        set(9, limit);
        set(10, coverimagekey);
        set(11, chargeimagekey);
        set(12, content);
        set(13, cancoverworkshop);
        set(14, ischarge);
        set(15, status);
        set(16, createtime);
    }
}
