/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.tools.dashboard.myspace.jooq;


import javax.annotation.Generated;

import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Attachment;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Clicklike;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Complain;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Gallery;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Gallerydetail;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.User;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.records.AttachmentRecord;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.records.ClicklikeRecord;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.records.ComplainRecord;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.records.GalleryRecord;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.records.GallerydetailRecord;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.records.UserRecord;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>myspace2</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AttachmentRecord, Integer> IDENTITY_ATTACHMENT = Identities0.IDENTITY_ATTACHMENT;
    public static final Identity<ClicklikeRecord, Integer> IDENTITY_CLICKLIKE = Identities0.IDENTITY_CLICKLIKE;
    public static final Identity<ComplainRecord, Integer> IDENTITY_COMPLAIN = Identities0.IDENTITY_COMPLAIN;
    public static final Identity<GalleryRecord, Integer> IDENTITY_GALLERY = Identities0.IDENTITY_GALLERY;
    public static final Identity<GallerydetailRecord, Integer> IDENTITY_GALLERYDETAIL = Identities0.IDENTITY_GALLERYDETAIL;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AttachmentRecord> KEY_ATTACHMENT_PRIMARY = UniqueKeys0.KEY_ATTACHMENT_PRIMARY;
    public static final UniqueKey<ClicklikeRecord> KEY_CLICKLIKE_PRIMARY = UniqueKeys0.KEY_CLICKLIKE_PRIMARY;
    public static final UniqueKey<ComplainRecord> KEY_COMPLAIN_PRIMARY = UniqueKeys0.KEY_COMPLAIN_PRIMARY;
    public static final UniqueKey<GalleryRecord> KEY_GALLERY_PRIMARY = UniqueKeys0.KEY_GALLERY_PRIMARY;
    public static final UniqueKey<GallerydetailRecord> KEY_GALLERYDETAIL_PRIMARY = UniqueKeys0.KEY_GALLERYDETAIL_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AttachmentRecord, Integer> IDENTITY_ATTACHMENT = createIdentity(Attachment.ATTACHMENT, Attachment.ATTACHMENT.ID);
        public static Identity<ClicklikeRecord, Integer> IDENTITY_CLICKLIKE = createIdentity(Clicklike.CLICKLIKE, Clicklike.CLICKLIKE.ID);
        public static Identity<ComplainRecord, Integer> IDENTITY_COMPLAIN = createIdentity(Complain.COMPLAIN, Complain.COMPLAIN.ID);
        public static Identity<GalleryRecord, Integer> IDENTITY_GALLERY = createIdentity(Gallery.GALLERY, Gallery.GALLERY.ID);
        public static Identity<GallerydetailRecord, Integer> IDENTITY_GALLERYDETAIL = createIdentity(Gallerydetail.GALLERYDETAIL, Gallerydetail.GALLERYDETAIL.ID);
        public static Identity<UserRecord, Integer> IDENTITY_USER = createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AttachmentRecord> KEY_ATTACHMENT_PRIMARY = createUniqueKey(Attachment.ATTACHMENT, "KEY_attachment_PRIMARY", Attachment.ATTACHMENT.ID);
        public static final UniqueKey<ClicklikeRecord> KEY_CLICKLIKE_PRIMARY = createUniqueKey(Clicklike.CLICKLIKE, "KEY_clicklike_PRIMARY", Clicklike.CLICKLIKE.ID);
        public static final UniqueKey<ComplainRecord> KEY_COMPLAIN_PRIMARY = createUniqueKey(Complain.COMPLAIN, "KEY_complain_PRIMARY", Complain.COMPLAIN.ID);
        public static final UniqueKey<GalleryRecord> KEY_GALLERY_PRIMARY = createUniqueKey(Gallery.GALLERY, "KEY_gallery_PRIMARY", Gallery.GALLERY.ID);
        public static final UniqueKey<GallerydetailRecord> KEY_GALLERYDETAIL_PRIMARY = createUniqueKey(Gallerydetail.GALLERYDETAIL, "KEY_gallerydetail_PRIMARY", Gallerydetail.GALLERYDETAIL.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
    }
}
