/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.tools.dashboard.myspace.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Attachment;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Clicklike;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Complain;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Gallery;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Gallerydetail;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.User;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Myspace2 extends SchemaImpl {

    private static final long serialVersionUID = -1050639988;

    /**
     * The reference instance of <code>myspace2</code>
     */
    public static final Myspace2 MYSPACE2 = new Myspace2();

    /**
     * The table <code>myspace2.attachment</code>.
     */
    public final Attachment ATTACHMENT = org.codeworks.web.tools.dashboard.myspace.jooq.tables.Attachment.ATTACHMENT;

    /**
     * The table <code>myspace2.clicklike</code>.
     */
    public final Clicklike CLICKLIKE = org.codeworks.web.tools.dashboard.myspace.jooq.tables.Clicklike.CLICKLIKE;

    /**
     * The table <code>myspace2.complain</code>.
     */
    public final Complain COMPLAIN = org.codeworks.web.tools.dashboard.myspace.jooq.tables.Complain.COMPLAIN;

    /**
     * The table <code>myspace2.gallery</code>.
     */
    public final Gallery GALLERY = org.codeworks.web.tools.dashboard.myspace.jooq.tables.Gallery.GALLERY;

    /**
     * The table <code>myspace2.gallerydetail</code>.
     */
    public final Gallerydetail GALLERYDETAIL = org.codeworks.web.tools.dashboard.myspace.jooq.tables.Gallerydetail.GALLERYDETAIL;

    /**
     * The table <code>myspace2.user</code>.
     */
    public final User USER = org.codeworks.web.tools.dashboard.myspace.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Myspace2() {
        super("myspace2", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Attachment.ATTACHMENT,
            Clicklike.CLICKLIKE,
            Complain.COMPLAIN,
            Gallery.GALLERY,
            Gallerydetail.GALLERYDETAIL,
            User.USER);
    }
}
