/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.tools.dashboard.myspace.jooq;


import javax.annotation.Generated;

import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Attachment;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Clicklike;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Complain;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Gallery;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.Gallerydetail;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.User;


/**
 * Convenience access to all tables in myspace2
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>myspace2.attachment</code>.
     */
    public static final Attachment ATTACHMENT = org.codeworks.web.tools.dashboard.myspace.jooq.tables.Attachment.ATTACHMENT;

    /**
     * The table <code>myspace2.clicklike</code>.
     */
    public static final Clicklike CLICKLIKE = org.codeworks.web.tools.dashboard.myspace.jooq.tables.Clicklike.CLICKLIKE;

    /**
     * The table <code>myspace2.complain</code>.
     */
    public static final Complain COMPLAIN = org.codeworks.web.tools.dashboard.myspace.jooq.tables.Complain.COMPLAIN;

    /**
     * The table <code>myspace2.gallery</code>.
     */
    public static final Gallery GALLERY = org.codeworks.web.tools.dashboard.myspace.jooq.tables.Gallery.GALLERY;

    /**
     * The table <code>myspace2.gallerydetail</code>.
     */
    public static final Gallerydetail GALLERYDETAIL = org.codeworks.web.tools.dashboard.myspace.jooq.tables.Gallerydetail.GALLERYDETAIL;

    /**
     * The table <code>myspace2.user</code>.
     */
    public static final User USER = org.codeworks.web.tools.dashboard.myspace.jooq.tables.User.USER;
}
