/*
 * This file is generated by jOOQ.
*/
package org.codeworks.web.tools.dashboard.myspace.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.codeworks.web.tools.dashboard.myspace.jooq.Keys;
import org.codeworks.web.tools.dashboard.myspace.jooq.Myspace2;
import org.codeworks.web.tools.dashboard.myspace.jooq.tables.records.GalleryRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gallery extends TableImpl<GalleryRecord> {

    private static final long serialVersionUID = -1136107815;

    /**
     * The reference instance of <code>myspace2.gallery</code>
     */
    public static final Gallery GALLERY = new Gallery();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GalleryRecord> getRecordType() {
        return GalleryRecord.class;
    }

    /**
     * The column <code>myspace2.gallery.id</code>.
     */
    public final TableField<GalleryRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>myspace2.gallery.openId</code>.
     */
    public final TableField<GalleryRecord, String> OPENID = createField("openId", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>myspace2.gallery.ada</code>.
     */
    public final TableField<GalleryRecord, String> ADA = createField("ada", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>myspace2.gallery.attachmentId</code>.
     */
    public final TableField<GalleryRecord, Integer> ATTACHMENTID = createField("attachmentId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>myspace2.gallery.chooseMusic</code>.
     */
    public final TableField<GalleryRecord, String> CHOOSEMUSIC = createField("chooseMusic", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>myspace2.gallery.galleryName</code>.
     */
    public final TableField<GalleryRecord, String> GALLERYNAME = createField("galleryName", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>myspace2.gallery.description</code>.
     */
    public final TableField<GalleryRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>myspace2.gallery.status</code>.
     */
    public final TableField<GalleryRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>myspace2.gallery.qrCodeKey</code>.
     */
    public final TableField<GalleryRecord, String> QRCODEKEY = createField("qrCodeKey", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>myspace2.gallery.createTime</code>.
     */
    public final TableField<GalleryRecord, Timestamp> CREATETIME = createField("createTime", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>myspace2.gallery.creatorId</code>.
     */
    public final TableField<GalleryRecord, Integer> CREATORID = createField("creatorId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>myspace2.gallery.updateTime</code>.
     */
    public final TableField<GalleryRecord, Timestamp> UPDATETIME = createField("updateTime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>myspace2.gallery.modifierId</code>.
     */
    public final TableField<GalleryRecord, Integer> MODIFIERID = createField("modifierId", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>myspace2.gallery</code> table reference
     */
    public Gallery() {
        this("gallery", null);
    }

    /**
     * Create an aliased <code>myspace2.gallery</code> table reference
     */
    public Gallery(String alias) {
        this(alias, GALLERY);
    }

    private Gallery(String alias, Table<GalleryRecord> aliased) {
        this(alias, aliased, null);
    }

    private Gallery(String alias, Table<GalleryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Myspace2.MYSPACE2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GalleryRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GALLERY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GalleryRecord> getPrimaryKey() {
        return Keys.KEY_GALLERY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GalleryRecord>> getKeys() {
        return Arrays.<UniqueKey<GalleryRecord>>asList(Keys.KEY_GALLERY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Gallery as(String alias) {
        return new Gallery(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Gallery rename(String name) {
        return new Gallery(name, null);
    }
}
